[package]
name = "bevy-particles"
version = "0.1.0"
edition = "2024"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 2

[dependencies]
bevy = "0.15.3"
rand = "0.9.0"
iyes_perf_ui = "0.4.0"
